# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Zhiyao Yin
email: zhiyao.yin.67@gmail.com
description: Personal homepage for Zhiyao Yin, a laser spectropist, data enthusiast and hobby programmer.
baseurl: # the optional subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Zhiyao Yin
  picture: "/assets/images/bio-photo.jpg"
  bio    : "Laser spectropist, data enthusiast and hobby programmer"
  location : "Stuttgart, Germany"
github_username: chuckedfromspace
linkedin_username: zhiyao-yin-5b5a084a

logo: # path of site logo, e.g. "/assets/images/logo.png"
search: # true, false (default)

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previsously gems
  - jekyll-sitemap


# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
